import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Image from "next/image";
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'County app',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <main>
            <nav className="bg-gray-500">
                <div className="container">
                    <div className="w-full flex items-center gap-3 py-4">
                        <Image src="/next.svg" alt="logo" width={48} height={48}/>
                        <h1>Country App</h1>
                    </div>
                </div>
            </nav>
        </main>
        {children}
        </body>
        </html>
    )
}
